### PR TITLE
Added markdown parser (unified + remark) in player to replace regex replaces

### PR DESCRIPTION
**Pull request by ivancea**
As commented in #150 
- Added `unified` and `remark-xxx` libraries to parse and re-convert to markdown after modifications
- Added `mdast-builder` for a functional markdown AST creation

### CODE REVIEW

**Comment by ivancea** [comment]
I'v changed some configurations and a dependency version:
- In `package.json`: `vscode` from `^1.1.25` to `^1.1.37`. The old version is giving me an erorr in its postinstall script (a 404 in a request it makes)
- In `tsconfig.json`:  Added the `esModuleInterop` option to be able to use the `import ... from ...` syntax instead of `import * as ... from ...` with the new dependencies (also, to avoid using the `require(...)` syntax

If you think any of those changes may be problematic, I'll undo them (if that's the case, please tell me which import/require syntax would you use)

**Comment by ivancea** [comment]
For now only the code fence part was replaced. If you think this approach is acceptable, I'll change the other regexes.

In the other hand, to replace the other regexes, I would like to know if there is any documentation about them. I understand the SHELL_SCRIPT one, but I'm not sure about the use case of the COMMAND and TOUR_REFERENCE ones

**Comment by lostintangent** [comment]
I just tried this branch, and it seems like [step references](https://github.com/microsoft/codetour#step-references) are broken. Are you seeing that behavior?

**Comment by ivancea** [comment]
> 
> 
> I just tried this branch, and it seems like [step references](https://github.com/microsoft/codetour#step-references) are broken. Are you seeing that behavior?

Fixed. The AST-to-string was scaping literal characters (square brackets not being part of a link), so the regex wasn't working.
I changed it to first apply the regex and then the AST.
Anyway, I wouldn't merge this until all the replace-like modifications are changed to the parser

**Comment by zubair1024** [comment]
Fff

**Pull request closed without merging**
